### PR TITLE
Add github action file for rspec

### PR DESCRIPTION
**Pull request by nevesenin**

### CODE REVIEW

**Comment by chrismo** [comment]
If we merge this, will it automatically start executing the GH action(s)?

**Comment by nevesenin** [comment]
I don't know yet, but I don't think so, since this usecase is worth a separate paragraph: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1
I'd like to change this PR to be a bit more restrictive. But I need to dig a bit more into the documentation. I'd like to start with running rspec only on new PRs and pushes to PRs and on merges to master.

**Comment by chrismo** [comment]
> I don't know yet, but I don't think so, since this usecase is worth a separate paragraph: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1 I'd like to change this PR to be a bit more restrictive. But I need to dig a bit more into the documentation. I'd like to start with running rspec only on new PRs and pushes to PRs and on merges to master.

Sounds good!

**Comment by nevesenin** [comment]
Closed this in favor of #9

**Pull request closed without merging**
